name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Install .NET Framework 4.6.1 Targeting Pack
      shell: powershell
      run: choco install netfx-4.6.1-devpack --yes --no-progress

    - name: Restore NuGet packages
      run: nuget restore MCAConverter.sln

    - name: Build
      run: msbuild MCAConverter.sln /p:Configuration=Release

    - name: Upload artifact
      uses: actions/upload-artifact@v5
      with:
        name: MCAConverter
        path: MCAConverter/bin/Release/
